pipeline {
    agent any

    environment {
        APP_NAME = "${{values.app_name}}".toLowerCase()
        DOCKER_IMAGE = "chaitanyapandeygspann/${APP_NAME}"
        DOCKER_TAG = "1.0.${BUILD_NUMBER}"
        IMAGE_TAG = "${DOCKER_IMAGE}:${DOCKER_TAG}"
        GITOPS_REPO = "https://github.com/Backstage-GoldenImage/k8s-artifact.git"
    }

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Debug Variables') {
            steps {
                sh '''
                echo "APP_NAME=$APP_NAME"
                echo "DOCKER_IMAGE=$DOCKER_IMAGE"
                echo "IMAGE_TAG=$IMAGE_TAG"
                '''
            }
        }

        stage('Detect Language') {
            steps {
             script {
         
              if (fileExists('package.json')) {
                env.LANG="node"
              }
         
              else if (fileExists('requirements.txt')) {
                env.LANG="python"
              }
         
              else if (fileExists('pom.xml')) {
                env.LANG="java"
              }
         
              else {
                error("Unsupported language")
              }
         
              echo "Detected language: ${env.LANG}"
             }
            }
        }
        
        stage('Build App') {
           steps {
            script {
        
             if (env.LANG == "node") {
               sh "npm install"
             }
        
             if (env.LANG == "python") {
               sh "pip install -r requirements.txt"
             }
        
             if (env.LANG == "java") {
               sh "mvn package"
             }
        
            }
           }
        }


        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t ${IMAGE_TAG} .
                '''
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push ${IMAGE_TAG}'
            }
        }

        stage('Update GitOps Repo') {
            steps {
                withCredentials([string(credentialsId: 'github-token', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                    rm -rf k8s-artifact

                    git clone --depth 1 https://${GITHUB_TOKEN}@github.com/Backstage-GoldenImage/k8s-artifact.git
                    cd k8s-artifact

                    mkdir -p apps/${APP_NAME}

                    cp -r ../manifest-templates/* apps/${APP_NAME}/

                    sed -i "s|\\${APP_NAME}|${APP_NAME}|g" apps/${APP_NAME}/*.yaml
                    sed -i "s|\\${DOCKER_IMAGE}|${IMAGE_TAG}|g" apps/${APP_NAME}/deployment.yaml

                    git config user.email "jenkins@local"
                    git config user.name "jenkins"

                    git add .
                    git commit -m "Deploy ${APP_NAME} build ${BUILD_NUMBER}" || true
                    git push origin main
                    '''
                }
            }
        }
    }

    post {
        always {
            sh "docker logout || true"
            sh "docker image prune -f || true"
        }
        success {
            echo "CI + CD pipeline completed successfully!"
        }
        failure {
            echo "Pipeline failed!"
        }
    }

}

